version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: final
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__UserContext: "Host=postgres;Username=postgres;Password=postgres;Database=scheduling_iam2;Port=5432;Include Error Detail=true"
    links:
      - postgres
      
  postgres:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scheduling_iam2
    volumes:
      - db:/var/lib/postgres/data
        
volumes:
  db: